# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Cygwin
nav:
- Introduction: index.md
- 'Install Cygwin': install/install.md
- 'User Environment': user-env/user-env.md
- 'Cygwin/Windows Integration': cygwin-windows/cygwin-windows.md
- 'Using Cygwin Command Line': using-cygwin-cl/using-cygwin-cl.md
- 'Using Cygwin X Windows': using-cygwin-xwin/using-cygwin-xwin.md
- 'Cygwin Development Environment': cygwin-dev-env/cygwin-dev-env.md
- 'Troubleshooting': troubleshooting/troubleshooting.md
- 'Resources': resources/resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based on theme.
extra_css:
- 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-geojson
site_author:  'Open Water Foundation'
site_description:  'OWF / Learn Cygwin'
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
